apiVersion: apps/v1
kind: Deployment
metadata:
  name: training-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: training-controller
  template:
    metadata:
      labels:
        app: training-controller
    spec:
      containers:
      - name: training-controller
        image: sanjayrancher/training-controller:v0.1-dev
        imagePullPolicy: Always
        env:
        - name: NATS_SERVER_URL
          value: "nats://nats_client:VfU6TcAl9x@nats-client.default.svc:4222"
        - name: MINIO_SERVER_URL
          value: "http://minio.default.svc.cluster.local:9000"
        - name: MINIO_ACCESS_KEY
          value: "myaccesskey"
        - name: MINIO_SECRET_KEY
          value: "mysecretkey"
        - name: JOB_NAMESPACE
          value: "default"
        - name: ES_ENDPOINT
          value: "https://opendistro-es-client-service.default.svc.cluster.local:9200"
        - name: ES_USERNAME
          value: "admin"
        - name: ES_PASSWORD
          value: "admin"
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: "0"
        - name: NULOG_TRAIN_IMAGE_REPO
          value: "sanjayrancher"
        - name: NULOG_TRAIN_IMAGE_NAME
          value: "nulog-train"
        - name: NULOG_TRAIN_IMAGE_TAG
          value: "v0.1-dev"
